<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../BlazorBarcodeScanner/BlazorBarcodeScanner.csproj" />
    <ProjectReference Include="../BlazorBarcodeScanner.TestKit/BlazorBarcodeScanner.TestKit.csproj" />
  </ItemGroup>

</Project>
