namespace BlazorBarcodeScanner.Decoding.Pdf417;

/// <summary>
/// Maps between PDF417 symbol characters (seventeen module bar and space patterns) and the
/// codeword values they stand for.
/// </summary>
/// <remarks>
/// <para>
/// <b>Important.</b> The assignment of the 2787 legal patterns to codeword values is pure table
/// data defined by ISO/IEC 15438; it cannot be derived from the structural rules. Verifying this
/// is easy: of the 10480 patterns that satisfy every structural constraint, the three usable
/// clusters hold 1484, 1002 and 1002 members, and no linear function of the eight element widths
/// selects 929 from each. The specification simply lists them.
/// </para>
/// <para>
/// The table this library ships is therefore a <b>placeholder</b>: it is generated by enumerating
/// the structurally valid patterns of each cluster in ascending numeric order. It is internally
/// consistent, so it round trips against the matching encoder and exercises every other part of
/// the PDF417 implementation, but it does <b>not</b> match the specification and will not read
/// real PDF417 symbols.
/// </para>
/// <para>
/// Call <see cref="Register"/> with the specification table to make PDF417 decoding conformant.
/// <see cref="Pipeline.BarcodeDecoder"/> only enables its PDF417 reader once
/// <see cref="IsSpecificationTable"/> is <see langword="true"/>, so nothing silently pretends to
/// scan PDF417 until that happens.
/// </para>
/// </remarks>
public sealed class Pdf417SymbolTable
{
    /// <summary>The three cluster numbers PDF417 uses.</summary>
    public static ReadOnlySpan<int> Clusters => [0, 3, 6];

    /// <summary>Number of codewords in a PDF417 symbol character set.</summary>
    public const int CodewordCount = 929;

    /// <summary>Number of modules in one symbol character.</summary>
    public const int ModulesPerCodeword = 17;

    private readonly Dictionary<int, int>[] _patternToCodeword;
    private readonly int[][] _codewordToPattern;

    private Pdf417SymbolTable(int[][] patternsByCluster, bool isSpecificationTable)
    {
        _codewordToPattern = patternsByCluster;
        _patternToCodeword = new Dictionary<int, int>[3];

        for (var c = 0; c < 3; c++)
        {
            var map = new Dictionary<int, int>(patternsByCluster[c].Length);
            for (var codeword = 0; codeword < patternsByCluster[c].Length; codeword++)
            {
                map[patternsByCluster[c][codeword]] = codeword;
            }

            _patternToCodeword[c] = map;
        }

        IsSpecificationTable = isSpecificationTable;
    }

    /// <summary>The table currently in use.</summary>
    public static Pdf417SymbolTable Current { get; private set; } = CreatePlaceholder();

    /// <summary>
    /// <see langword="false"/> for the generated placeholder that ships with the library, and
    /// <see langword="true"/> only for a table supplied from ISO/IEC 15438.
    /// </summary>
    public bool IsSpecificationTable { get; }

    /// <summary>
    /// Installs a symbol character table.
    /// </summary>
    /// <param name="table">The table to use from now on.</param>
    /// <remarks>
    /// This is a process wide setting and is meant to be called once during start-up, before any
    /// scanner is created.
    /// </remarks>
    public static void Register(Pdf417SymbolTable table)
    {
        ArgumentNullException.ThrowIfNull(table);
        Current = table;
    }

    /// <summary>
    /// Builds a table from the specification's pattern lists.
    /// </summary>
    /// <param name="cluster0">The 929 seventeen bit patterns of cluster 0, indexed by codeword value.</param>
    /// <param name="cluster3">The 929 patterns of cluster 3.</param>
    /// <param name="cluster6">The 929 patterns of cluster 6.</param>
    /// <param name="isSpecificationTable">
    /// Whether these patterns come from ISO/IEC 15438. Only pass <see langword="true"/> when they do.
    /// </param>
    public static Pdf417SymbolTable FromPatterns(
        int[] cluster0, int[] cluster3, int[] cluster6, bool isSpecificationTable)
    {
        ArgumentNullException.ThrowIfNull(cluster0);
        ArgumentNullException.ThrowIfNull(cluster3);
        ArgumentNullException.ThrowIfNull(cluster6);

        foreach (var (patterns, name) in new[] { (cluster0, nameof(cluster0)), (cluster3, nameof(cluster3)), (cluster6, nameof(cluster6)) })
        {
            if (patterns.Length != CodewordCount)
            {
                throw new ArgumentException($"A PDF417 cluster holds exactly {CodewordCount} patterns.", name);
            }
        }

        return new Pdf417SymbolTable([cluster0, cluster3, cluster6], isSpecificationTable);
    }

    /// <summary>Looks up the codeword a pattern stands for.</summary>
    /// <param name="cluster">The cluster number: 0, 3 or 6.</param>
    /// <param name="pattern">The seventeen bit module pattern, most significant bit first, starting with a bar.</param>
    /// <param name="codeword">The codeword value, 0 to 928.</param>
    public bool TryGetCodeword(int cluster, int pattern, out int codeword)
    {
        codeword = -1;
        var index = ClusterIndex(cluster);
        return index >= 0 && _patternToCodeword[index].TryGetValue(pattern, out codeword);
    }

    /// <summary>Looks up the pattern for a codeword. Used by encoders and by the round trip tests.</summary>
    /// <param name="cluster">The cluster number: 0, 3 or 6.</param>
    /// <param name="codeword">The codeword value, 0 to 928.</param>
    /// <param name="pattern">The seventeen bit module pattern.</param>
    public bool TryGetPattern(int cluster, int codeword, out int pattern)
    {
        pattern = 0;
        var index = ClusterIndex(cluster);
        if (index < 0 || (uint)codeword >= (uint)_codewordToPattern[index].Length)
        {
            return false;
        }

        pattern = _codewordToPattern[index][codeword];
        return true;
    }

    private static int ClusterIndex(int cluster) => cluster switch
    {
        0 => 0,
        3 => 1,
        6 => 2,
        _ => -1,
    };

    /// <summary>
    /// Builds the generated placeholder table by enumerating the structurally valid symbol
    /// characters of each cluster in ascending numeric order.
    /// </summary>
    /// <remarks>
    /// A valid symbol character is four bars and four spaces, starting with a bar, each between
    /// one and six modules wide, totalling seventeen modules, whose cluster number
    /// <c>(b1 - b2 + b3 - b4) mod 9</c> is 0, 3 or 6.
    /// </remarks>
    public static Pdf417SymbolTable CreatePlaceholder()
    {
        var byCluster = new List<int>[3];
        for (var i = 0; i < 3; i++)
        {
            byCluster[i] = new List<int>(1500);
        }

        Span<int> widths = stackalloc int[8];
        Enumerate(widths, 0, 0);

        var patterns = new int[3][];
        for (var i = 0; i < 3; i++)
        {
            byCluster[i].Sort();
            patterns[i] = [.. byCluster[i].Take(CodewordCount)];
        }

        return new Pdf417SymbolTable(patterns, isSpecificationTable: false);

        void Enumerate(Span<int> current, int index, int total)
        {
            if (index == 8)
            {
                if (total != ModulesPerCodeword)
                {
                    return;
                }

                var cluster = ((current[0] - current[2] + current[4] - current[6]) % 9 + 9) % 9;
                var clusterIndex = ClusterIndex(cluster);
                if (clusterIndex < 0)
                {
                    return;
                }

                byCluster[clusterIndex].Add(ToPattern(current));
                return;
            }

            // Prune branches that already exceed the module budget or cannot reach it.
            var remaining = 8 - index;
            for (var width = 1; width <= 6; width++)
            {
                var next = total + width;
                if (next + remaining - 1 > ModulesPerCodeword || next + (6 * (remaining - 1)) < ModulesPerCodeword)
                {
                    continue;
                }

                current[index] = width;
                Enumerate(current, index + 1, next);
            }
        }
    }

    /// <summary>Packs eight element widths into the seventeen bit pattern, bar first.</summary>
    /// <param name="widths">Element widths in modules, bar first, summing to seventeen.</param>
    public static int ToPattern(ReadOnlySpan<int> widths)
    {
        var pattern = 0;
        var bit = ModulesPerCodeword - 1;
        var bar = true;

        foreach (var width in widths)
        {
            for (var i = 0; i < width; i++)
            {
                if (bar)
                {
                    pattern |= 1 << bit;
                }

                bit--;
            }

            bar = !bar;
        }

        return pattern;
    }

    /// <summary>Computes the cluster number from the four bar widths of a symbol character.</summary>
    /// <param name="widths">Element widths in modules, bar first.</param>
    public static int ClusterOf(ReadOnlySpan<int> widths) =>
        (((widths[0] - widths[2] + widths[4] - widths[6]) % 9) + 9) % 9;
}
