<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/BlazorScanner/BlazorScanner.csproj" />
    <ProjectReference Include="../../tests/BlazorScanner.TestKit/BlazorScanner.TestKit.csproj" />
  </ItemGroup>

</Project>
